/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_statement_dialog_close = 2,
  anon_sym_label = 3,
  anon_sym_print = 4,
  anon_sym_return = 5,
  sym_assigner = 6,
  anon_sym_DOT = 7,
  aux_sym_string_rich_token1 = 8,
  aux_sym_string_rich_token2 = 9,
  sym_string_raw = 10,
  aux_sym_number_token1 = 11,
  aux_sym_number_token2 = 12,
  aux_sym_number_token3 = 13,
  anon_sym_POUND = 14,
  aux_sym_comment_token1 = 15,
  sym__string_rich_implicit = 16,
  sym__line_indent = 17,
  sym_source_file = 18,
  sym__statement = 19,
  sym_statement_assign = 20,
  sym_statement_dialog = 21,
  sym_statement_label = 22,
  sym__statement_path = 23,
  sym_statement_print = 24,
  sym_statement_return = 25,
  sym_expression = 26,
  sym__keyword_label = 27,
  sym__keyword_print = 28,
  sym__keyword_return = 29,
  sym_path = 30,
  sym__operator_dot = 31,
  sym__string = 32,
  sym_string_rich = 33,
  sym_number = 34,
  sym_comment = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_path_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_statement_dialog_close] = "statement_dialog_close",
  [anon_sym_label] = "keyword",
  [anon_sym_print] = "keyword",
  [anon_sym_return] = "keyword",
  [sym_assigner] = "assigner",
  [anon_sym_DOT] = "operator",
  [aux_sym_string_rich_token1] = "string_rich_token1",
  [aux_sym_string_rich_token2] = "string_rich_token2",
  [sym_string_raw] = "string_raw",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__string_rich_implicit] = "_string_rich_implicit",
  [sym__line_indent] = "_line_indent",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_statement_assign] = "statement_assign",
  [sym_statement_dialog] = "statement_dialog",
  [sym_statement_label] = "statement_label",
  [sym__statement_path] = "_statement_path",
  [sym_statement_print] = "statement_print",
  [sym_statement_return] = "statement_return",
  [sym_expression] = "expression",
  [sym__keyword_label] = "_keyword_label",
  [sym__keyword_print] = "_keyword_print",
  [sym__keyword_return] = "_keyword_return",
  [sym_path] = "path",
  [sym__operator_dot] = "_operator_dot",
  [sym__string] = "_string",
  [sym_string_rich] = "string_rich",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_statement_dialog_close] = sym_statement_dialog_close,
  [anon_sym_label] = anon_sym_label,
  [anon_sym_print] = anon_sym_label,
  [anon_sym_return] = anon_sym_label,
  [sym_assigner] = sym_assigner,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_string_rich_token1] = aux_sym_string_rich_token1,
  [aux_sym_string_rich_token2] = aux_sym_string_rich_token2,
  [sym_string_raw] = sym_string_raw,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__string_rich_implicit] = sym__string_rich_implicit,
  [sym__line_indent] = sym__line_indent,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_statement_assign] = sym_statement_assign,
  [sym_statement_dialog] = sym_statement_dialog,
  [sym_statement_label] = sym_statement_label,
  [sym__statement_path] = sym__statement_path,
  [sym_statement_print] = sym_statement_print,
  [sym_statement_return] = sym_statement_return,
  [sym_expression] = sym_expression,
  [sym__keyword_label] = sym__keyword_label,
  [sym__keyword_print] = sym__keyword_print,
  [sym__keyword_return] = sym__keyword_return,
  [sym_path] = sym_path,
  [sym__operator_dot] = sym__operator_dot,
  [sym__string] = sym__string,
  [sym_string_rich] = sym_string_rich,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_dialog_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_assigner] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_rich_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_rich_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_string_raw] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__string_rich_implicit] = {
    .visible = false,
    .named = true,
  },
  [sym__line_indent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_statement_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_label] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_path] = {
    .visible = false,
    .named = true,
  },
  [sym_statement_print] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_return] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__keyword_label] = {
    .visible = false,
    .named = true,
  },
  [sym__keyword_print] = {
    .visible = false,
    .named = true,
  },
  [sym__keyword_return] = {
    .visible = false,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym__operator_dot] = {
    .visible = false,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym_string_rich] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '#', 18,
        '+', 12,
        '-', 7,
        '.', 10,
        '=', 9,
        '>', 11,
        '`', 2,
        '"', 3,
        '\'', 3,
        '&', 1,
        '*', 1,
        '/', 1,
        '?', 1,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '`') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_statement_dialog_close);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_statement_dialog_close);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_assigner);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_string_rich_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_rich_token1);
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_rich_token2);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string_raw);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'l') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_label);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 20, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_statement_dialog_close] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_assigner] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_string_rich_token1] = ACTIONS(1),
    [aux_sym_string_rich_token2] = ACTIONS(1),
    [sym_string_raw] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [sym__string_rich_implicit] = ACTIONS(1),
    [sym__line_indent] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym__statement] = STATE(16),
    [sym_statement_assign] = STATE(18),
    [sym_statement_dialog] = STATE(18),
    [sym_statement_label] = STATE(18),
    [sym__statement_path] = STATE(18),
    [sym_statement_print] = STATE(18),
    [sym_statement_return] = STATE(18),
    [sym__keyword_label] = STATE(30),
    [sym__keyword_print] = STATE(26),
    [sym__keyword_return] = STATE(4),
    [sym_path] = STATE(11),
    [sym__operator_dot] = STATE(33),
    [sym__string] = STATE(17),
    [sym_string_rich] = STATE(14),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_statement_dialog_close] = ACTIONS(11),
    [anon_sym_label] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(19),
    [aux_sym_string_rich_token1] = ACTIONS(21),
    [aux_sym_string_rich_token2] = ACTIONS(23),
    [sym_string_raw] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(3),
    [sym__line_indent] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(16),
    [sym_statement_assign] = STATE(18),
    [sym_statement_dialog] = STATE(18),
    [sym_statement_label] = STATE(18),
    [sym__statement_path] = STATE(18),
    [sym_statement_print] = STATE(18),
    [sym_statement_return] = STATE(18),
    [sym__keyword_label] = STATE(30),
    [sym__keyword_print] = STATE(26),
    [sym__keyword_return] = STATE(4),
    [sym_path] = STATE(11),
    [sym__operator_dot] = STATE(33),
    [sym__string] = STATE(17),
    [sym_string_rich] = STATE(14),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(9),
    [sym_statement_dialog_close] = ACTIONS(11),
    [anon_sym_label] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(19),
    [aux_sym_string_rich_token1] = ACTIONS(21),
    [aux_sym_string_rich_token2] = ACTIONS(23),
    [sym_string_raw] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(3),
    [sym__line_indent] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(16),
    [sym_statement_assign] = STATE(18),
    [sym_statement_dialog] = STATE(18),
    [sym_statement_label] = STATE(18),
    [sym__statement_path] = STATE(18),
    [sym_statement_print] = STATE(18),
    [sym_statement_return] = STATE(18),
    [sym__keyword_label] = STATE(30),
    [sym__keyword_print] = STATE(26),
    [sym__keyword_return] = STATE(4),
    [sym_path] = STATE(11),
    [sym__operator_dot] = STATE(33),
    [sym__string] = STATE(17),
    [sym_string_rich] = STATE(14),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_statement_dialog_close] = ACTIONS(34),
    [anon_sym_label] = ACTIONS(37),
    [anon_sym_print] = ACTIONS(40),
    [anon_sym_return] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(46),
    [aux_sym_string_rich_token1] = ACTIONS(49),
    [aux_sym_string_rich_token2] = ACTIONS(52),
    [sym_string_raw] = ACTIONS(55),
    [anon_sym_POUND] = ACTIONS(3),
    [sym__line_indent] = ACTIONS(5),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(24),
    [sym_path] = STATE(23),
    [sym__operator_dot] = STATE(33),
    [sym_number] = STATE(23),
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(58),
    [sym_identifier] = ACTIONS(60),
    [sym_statement_dialog_close] = ACTIONS(58),
    [anon_sym_label] = ACTIONS(60),
    [anon_sym_print] = ACTIONS(60),
    [anon_sym_return] = ACTIONS(60),
    [anon_sym_DOT] = ACTIONS(60),
    [aux_sym_string_rich_token1] = ACTIONS(58),
    [aux_sym_string_rich_token2] = ACTIONS(58),
    [sym_string_raw] = ACTIONS(58),
    [aux_sym_number_token1] = ACTIONS(62),
    [aux_sym_number_token2] = ACTIONS(64),
    [aux_sym_number_token3] = ACTIONS(64),
    [anon_sym_POUND] = ACTIONS(3),
    [sym__line_indent] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(5), 1,
      sym_comment,
    ACTIONS(68), 6,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      anon_sym_DOT,
      aux_sym_number_token1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
      aux_sym_number_token2,
      aux_sym_number_token3,
  [27] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(19), 1,
      anon_sym_DOT,
    STATE(6), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_path_repeat1,
    STATE(34), 1,
      sym__operator_dot,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      sym_assigner,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(72), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [60] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(19), 1,
      anon_sym_DOT,
    STATE(7), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_path_repeat1,
    STATE(34), 1,
      sym__operator_dot,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      sym_assigner,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(76), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [93] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(8), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_path_repeat1,
    STATE(34), 1,
      sym__operator_dot,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      sym_assigner,
      anon_sym_DOT,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(76), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [124] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(34), 1,
      sym__operator_dot,
    STATE(9), 2,
      sym_comment,
      aux_sym_path_repeat1,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      sym_assigner,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(80), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [155] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(9), 1,
      aux_sym_path_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(34), 1,
      sym__operator_dot,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      sym_assigner,
      anon_sym_DOT,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(87), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [186] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(93), 1,
      sym_assigner,
    STATE(11), 1,
      sym_comment,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      anon_sym_DOT,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(91), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [213] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(99), 1,
      sym__string_rich_implicit,
    STATE(12), 1,
      sym_comment,
    ACTIONS(97), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [240] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(13), 1,
      sym_comment,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      sym_assigner,
      anon_sym_DOT,
      aux_sym_string_rich_token2,
      sym_string_raw,
    ACTIONS(80), 6,
      sym_statement_dialog_close,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
      aux_sym_string_rich_token1,
  [265] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(14), 1,
      sym_comment,
    ACTIONS(103), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [289] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(15), 1,
      sym_comment,
    ACTIONS(97), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [313] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(16), 1,
      sym_comment,
    ACTIONS(107), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [337] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(17), 1,
      sym_comment,
    ACTIONS(111), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [361] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(18), 1,
      sym_comment,
    ACTIONS(115), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [385] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(19), 1,
      sym_comment,
    ACTIONS(119), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [409] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(20), 1,
      sym_comment,
    ACTIONS(123), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [433] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(21), 1,
      sym_comment,
    ACTIONS(127), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [457] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(22), 1,
      sym_comment,
    ACTIONS(131), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [481] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(23), 1,
      sym_comment,
    ACTIONS(135), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [505] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(24), 1,
      sym_comment,
    ACTIONS(139), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [529] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(25), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_label,
      anon_sym_print,
      anon_sym_return,
      sym_identifier,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      sym_statement_dialog_close,
      anon_sym_DOT,
      aux_sym_string_rich_token1,
      aux_sym_string_rich_token2,
      sym_string_raw,
  [553] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(62), 1,
      aux_sym_number_token1,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_DOT,
    STATE(22), 1,
      sym_expression,
    STATE(26), 1,
      sym_comment,
    STATE(33), 1,
      sym__operator_dot,
    ACTIONS(64), 2,
      aux_sym_number_token2,
      aux_sym_number_token3,
    STATE(23), 2,
      sym_path,
      sym_number,
  [586] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(62), 1,
      aux_sym_number_token1,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_DOT,
    STATE(25), 1,
      sym_expression,
    STATE(27), 1,
      sym_comment,
    STATE(33), 1,
      sym__operator_dot,
    ACTIONS(64), 2,
      aux_sym_number_token2,
      aux_sym_number_token3,
    STATE(23), 2,
      sym_path,
      sym_number,
  [619] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    STATE(28), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_DOT,
      aux_sym_number_token1,
    ACTIONS(149), 3,
      sym_identifier,
      aux_sym_number_token2,
      aux_sym_number_token3,
  [638] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(29), 1,
      sym_comment,
  [651] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(30), 1,
      sym_comment,
  [664] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_comment,
  [677] = 4,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(159), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      aux_sym_comment_token1,
    STATE(32), 1,
      sym_comment,
  [690] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(163), 1,
      sym_identifier,
    STATE(33), 1,
      sym_comment,
  [703] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(165), 1,
      sym_identifier,
    STATE(34), 1,
      sym_comment,
  [716] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym__line_indent,
    ACTIONS(167), 1,
      sym_identifier,
    STATE(35), 1,
      sym_comment,
  [729] = 1,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 27,
  [SMALL_STATE(7)] = 60,
  [SMALL_STATE(8)] = 93,
  [SMALL_STATE(9)] = 124,
  [SMALL_STATE(10)] = 155,
  [SMALL_STATE(11)] = 186,
  [SMALL_STATE(12)] = 213,
  [SMALL_STATE(13)] = 240,
  [SMALL_STATE(14)] = 265,
  [SMALL_STATE(15)] = 289,
  [SMALL_STATE(16)] = 313,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 361,
  [SMALL_STATE(19)] = 385,
  [SMALL_STATE(20)] = 409,
  [SMALL_STATE(21)] = 433,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 481,
  [SMALL_STATE(24)] = 505,
  [SMALL_STATE(25)] = 529,
  [SMALL_STATE(26)] = 553,
  [SMALL_STATE(27)] = 586,
  [SMALL_STATE(28)] = 619,
  [SMALL_STATE(29)] = 638,
  [SMALL_STATE(30)] = 651,
  [SMALL_STATE(31)] = 664,
  [SMALL_STATE(32)] = 677,
  [SMALL_STATE(33)] = 690,
  [SMALL_STATE(34)] = 703,
  [SMALL_STATE(35)] = 716,
  [SMALL_STATE(36)] = 729,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_return, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_return, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__keyword_return, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__keyword_return, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_path, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_path, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_rich, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_rich, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_dialog, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_dialog, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_rich, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_rich, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_label, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_label, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_print, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_print, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_return, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_return, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_assign, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_assign, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__keyword_print, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__keyword_print, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operator_dot, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [157] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__keyword_label, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__string_rich_implicit = 0,
  ts_external_token__line_indent = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__string_rich_implicit] = sym__string_rich_implicit,
  [ts_external_token__line_indent] = sym__line_indent,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__string_rich_implicit] = true,
    [ts_external_token__line_indent] = true,
  },
  [2] = {
    [ts_external_token__line_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_penny_external_scanner_create(void);
void tree_sitter_penny_external_scanner_destroy(void *);
bool tree_sitter_penny_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_penny_external_scanner_serialize(void *, char *);
void tree_sitter_penny_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_penny(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_penny_external_scanner_create,
      tree_sitter_penny_external_scanner_destroy,
      tree_sitter_penny_external_scanner_scan,
      tree_sitter_penny_external_scanner_serialize,
      tree_sitter_penny_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "penny",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
